@startuml
'https://plantuml.com/class-diagram

class Ship {
 -shipName : String
 -yearBuilt : String

 +getShipName() : String
 +setShipName(name : String) : void
 +getYearBuilt() : String
 +setYearBuilt(yearBuilt : String) : void
 +toString() : String
 +printShip() : void
}

class CruiseShip extends Ship {
 -maxNumberPassengers : int

 +getMaxNumberPassengers() : int
 +setMaxNumberPassengers(maxNumberPassengers : int) : void
 +toString() : String
}

class CargoShip extends Ship {
 -cargoCapacityInTonnage : int

 +getCargoCapacityInTonnage() : int
 +setCargoCapacityInTonnage(cargoCapacity : int) : void
 +toString() : String
}

@enduml