@startuml
'https://plantuml.com/object-diagram



object "phpDemo1: Folder" as phpDemo1 {
    name = "php_demo1"
    subfolders = [sourceFiles, includePath, remoteFiles]
    files = []
}

object "Source Files: Folder" as sourceFiles{
    name = "Source Files"
    subfolders = [phalcon, app, cache, public]
    files = []
}
object "Include Path: Folder" as includePath{
    name = "Include Path"
    subfolders = []
    files = []
}
object "app: Folder" as app{
    name = "app"
    subfolders = []
    files = []
}
object "Remote Files: Folder" as remoteFiles{
    name = "Remote Files"
    subfolders = []
    files = []
}

object ".phalcon: Folder" as .phalcon{
    name = ".phalcon"
    subfolders = []
    files = []
}
object "cache: Folder" as cache{
    name = "cache"
    subfolders = []
    files = []
}
object "public: Folder" as public{
    name = "public"
    subfolders = []
    files = [.htaccess, .htrouter.php, index.html]
}

object ".htaccess: File" as file1{
    name = ".htaccess"
}
object ".htrouter.php: File" as file2{
    name = ".htrouter.php"
}
object "index.html: File" as file3{
    name = "index.html"
}

phpDemo1 *-- sourceFiles
phpDemo1 *-- includePath
phpDemo1 *-- remoteFiles

sourceFiles *-- .phalcon
sourceFiles *-- app
sourceFiles *-- cache
sourceFiles *-- public

public *-- file1
public *-- file2
public *-- file3

@enduml
